CREATE SEQUENCE dim_customers_seq
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE dim_offices_seq
 START WITH     100
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE dim_products_seq
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
CREATE SEQUENCE dim_employees_seq
 START WITH     1000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
