-- INSERT DIM_EMPLOYEES SPECIAL ROW
INSERT INTO SYVH_DIM_EMPLOYEES 
VALUES (0, 0, 'Unknown', 'Unknown', 'Unknown', 'Unknown', '0', 0, 'Unknown', '1', TO_DATE('1-1-1900', 'DD-MM-YYYY'), TO_DATE('1-1-2400', 'DD-MM-YYYY')); 

-- INSERT DIM_CUSTOMERS SPECIAL ROW
INSERT INTO SYVH_DIM_CUSTOMERS
VALUES (0, 0, );

-- INSERT DIM_DATE SPECIAL ROW
INSERT INTO SYVH_DIM_DATE (DATE_VALUE, DATE_KEY)
VALUES (0, TO_DATE('2099-01-01', 'YYYY-MM-DD'));
